version: "3.9"

services:
  db:
    image: postgres:15
    container_name: rsshub-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration/create_feeds_table.up.sql:/docker-entrypoint-initdb.d/create_feeds_table.sql:ro

  app:
    build: .
    container_name: rsshub-app
    depends_on:
      - db
    env_file:
      - .env
    command: ["./rsshub"]

volumes:
  postgres_data:
